config/routes.rb
Loja::Application.routes.draw do

resources :produtos
resources :itens do
  collection do
    put :atualizar_todos
  end
end
  namespace :admin do
  resources :categorias
  resources :produtos
end

root :to => 'produtos#index'

end

app/controllers/admin/base_controller.rb
class Admin::BaseController <ApplicationController

	layout 'administracao'

end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::CrudController

protected
def record_type
	Categoria
end

end

app/controllers/admin/crud_controller.rb
#encoding: utf-8
class Admin::CrudController < Admin::BaseController

	before_filter :load_record, 
	:only => [:new, :edit, :create, :update, :destroy]

	def index
		@records = paginar(record_type)
	end

	def new
		render :new
	end

	alias :edit :new

	def create

		if @record.update_attributes(params[record_name])
			flash[:success] = "#{record_human_name} foi salvo com sucesso"
			redirect_to send("admin_#{record_name_plural}_path")
		else
			flash.now[:error] =	'Ocorreram erros na hora de gravar o produto'
			render :new
		end

	end

	alias :update :create

	def destroy
		@record.destroy
		flash[:success] = "#{record_human_name} foi removido com sucesso"
		redirect_to send("admin_#{record_name_plural}_path")

	end

	protected

	def load_record
		@record = if params[:id].blank?
			record_type.new
		else
			record_type.find(params[:id])
		end
	end

	def record_type
		raise %Q! Voce deve implementar esse metodo, como em : def record_type Produto end!
	end

	def record_human_name
		record_type.model_name.i18n_key
	end

	def record_name
		record_type.model_name.i18n_key
	end

	def record_name_plural
		record_type.model_name.plural
	end

end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < Admin::CrudController

	protected

	def record_type
		Produto
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :pedido_atual

	protected

	def carregar_pagina
		@pagina = params[:page] || 1
		@por_pagina = params[:per_page] || 10
	end

	def paginar(clazz)
		carregar_pagina
		clazz.paginate(
			:page => @pagina,
			:per_page => @por_pagina )
	end
	
	def pedido_atual
		if @pedido_atual.nil? && !session[:pedido_atual_id].nil?
			@pedido_atual = Pedido.find_by_id( session[:pedido_atual_id] )
		end
		@pedido_atual ||= Pedido.new
	end

end

app/controllers/itens_controller.rb
class ItensController < ApplicationController

  def index
  end

  def destroy
    @item = pedido_atual.itens.find(params[:id])
    @item.destroy

    flash[:success] = "Item #{@item.nome} removido com sucesso"
    redirect_to itens_path
  end

  def atualizar_todos
    pedido_atual.itens_attributes =
        params[:pedido][:itens_attributes]
    pedido_atual.save!

    flash[:success] = 'Quantidades atualizadas com sucesso'
    redirect_to itens_path
  end

  def create

    if self.pedido_atual.new_record?
      self.pedido_atual.save!
      session[:pedido_atual_id] = self.pedido_atual.id
    end

    @produto = Produto.find( params[:produto_id] )
    @quantidade = params[:quantidade]
    self.pedido_atual.adicionar_produto( @produto, @quantidade )

    respond_to do |format|
      format.html do
        flash[:success] = %Q!O produto #{@produto.nome} foi
          adicionado com sucesso no seu carrinho!
        redirect_to itens_path
      end
    end

  end

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

	def index
		@produtos = Produto.all
		respond_to do |format|
			format.html
			format.json {render :json => :produtos}
			format.xml { render :xml => :produtos}
		end
	end

	def show
		@produto_id = params[:id]
		@produto = Produto.find(@produto_id)
		
	end

end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper

	def admin_form_for(record, &block)
		form_for( record,
				:url => [:admin, record],
				:html => {
					:class => 'form-horizontal',
					:multipart => true
					}, :builder => BootstrapFormBuilder, &block)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  IGNORED_COLUMNS = [ 'id', 'update_at', 'created_at']

  def render_head(clazz, * columns)

  	if columns.blank?
  		columns = clazz.column_names - IGNORED_COLUMNS
	end
    content_tag :thead do
      content_tag :tr do
        table_headers = columns.map do |column|
          content_tag(
              :th,
              clazz.human_attribute_name(column))
        end

        table_headers.join("\n").html_safe
      end
    end

  end
end

app/views/admin/categorias/index.html.erb
<h2> Administracao De Produtos </h2>

<%= will_paginate @records %>
<div class "well">
	<%= link_to 'Nova Categoria', 
				new_admin_categoria_path,
				:class => 'btn btn-primary' %>
</div>

<table class = "table table-bordered table striped ">
<%= render_head Categoria, :nome %>


	<tbody>
		<% @records.each do |record| %>
		<tr>
			<td> <%= record.nome %> </td>
			<td> 
				<%= link_to 'Editar', 
							edit_admin_categoria_path(record), 
							:class => 'btn btn-primary' %>
				<%= link_to 'Remover',
							admin_categoria_path(record),
							:method => :delete,
							:data => {:confirm => 'Tem Certeza'},
							:class => 'btn btn-danger' %>
			</td>

		</tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @records %>

app/views/admin/categorias/new.html.erb
<h2>
		Nova <%= @record.class.model_name %>
</h2>


<%= admin_form_for @record do |f| %>

		<%= f.text_field :nome %>
	


	<div class="form-actions">
		<%= f.submit 'Enviar', :class => "btn btn-primary" %>
	</div>

<% end %>

app/views/admin/produtos/index.html.erb
<h2> Administracao De Produtos </h2>

<%= will_paginate @records %>
<div class "well">
	<%= link_to 'Novo Produto', 
				new_admin_produto_path,
				:class => 'btn btn-primary' %>
</div>

<table class = "table table-bordered table striped ">
<%= render_head Produto,
:nome,
:preco, 
:categoria_id %>


	<tbody>
		<% @records.each do |produto| %>
		<tr>
			<td> <%= produto.nome %> </td>
			<td><%= produto.categoria ? produto.categoria.nome : '-' %></td>
			<td> <%= number_to_currency produto.preco %></td>
			<td> 
				<%= link_to 'Editar', 
							edit_admin_produto_path(produto), 
							:class => 'btn btn-primary' %>
				<%= link_to 'Remover',
							admin_produto_path(produto),
							:method => :delete,
							:data => {:confirm => 'Tem Certeza'},
							:class => 'btn btn-danger' %>
			</td>

		</tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @records %>

app/views/admin/produtos/new.html.erb
<h2>
		Novo <%= @record.class.model_name %>
</h2>


<%= admin_form_for @record do |f| %>

	<%= f.text_field :nome %>
	<%= f.text_field :preco %>
	<%= f.text_area :descricao, :rows => 3 %>
	<%= f.select :categoria_id,
				Categoria.all.map{|c| [c.nome, c.id]},
				:include_blank => 'Selecione a categoria'%>

	<div class "form-actions">
		<%= f.primary_submit 'Enviar'%>
	</div>

<% end %>

app/views/compartilhados/_admin_navbar.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Loja', root_url, :class => 'brand' %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">
                <%= link_to 'Produtos', admin_produtos_url %>
              </li>
            	</ul>
          </div>
        </div>
      </div>
    </div>

app/views/compartilhados/_mensagens.html.haml
- [:error, :success, :info].each do |key|
	- unless flash[key].blank?
		%div{ :class => "alert alert-#{key}"}
			%a.close{'data.dismiss' => 'alert', 'href' => '#'}
				x
			= flash[key] 

app/views/compartilhados/_navbar.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Loja', root_url, :class => 'brand' %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">
                <%= link_to 'Produtos', produtos_url %>
              </li>
            </ul>
            <ul class="nav pull-right">
            	<li class="divider-vertical"></li>
            		<li>
            			<%= link_to 'Carrinho De Compras', itens_url %>
            		</li>
            	</ul>
          </div>
        </div>
      </div>
    </div>

app/views/compartilhados/_old_mensagens.html.erb
<% [:error, :success, :info].each do |key| %>
	<% unless flash[key].blank? %>
	<div class = "alert alert-<%= key %>">
		<a class = "close" data-dismiss = "alert" href="#">x</a>
		<%= flash[key] %>
	</div>
	<% end %>
<% end %>

app/views/itens/_item.html.erb
<tr>
  <td><%= item.nome %></td>
  <td><%= number_to_currency item.preco_unitario %></td>
  <td>
    <%= item_form.hidden_field :id %>
    <%= item_form.text_field :quantidade  %>
  	<%= item_form.submit 'Atualizar', :class => 'btn btn-primary' %>
  	<%= link_to 'Remover', item_path(item),
  	:method => :delete,
  	:data => { :confirm =>'tem certeza?'},
  	:class => 'btn btn-danger' %>
  </td>
  <td><%= number_to_currency item.preco_total %></td>
</tr>

app/views/itens/index.html.erb
<h2>Meu carrinho de compras</h2>

<%= form_for pedido_atual, :namespace => :pedido,
        :url => atualizar_todos_itens_url do |f| %>
    <table class="table table-striped table-bordered">
      <%= render_head(Item, :nome, :preco_unitario, :quantidade,
              :preco_total) %>
      <tbody>

      <% pedido_atual.itens.each do |i| %>
          <%= f.fields_for 'itens_attributes[]', i do |item_form| %>
              <%= render 'item', :item => i, :item_form => item_form %>
          <% end %>
      <% end %>

      </tbody>
      <tfoot>
      <tr>
        <td colspan="2"></td>
        <td>Preço Total</td>
        <td> <%= number_to_currency pedido_atual.preco_total %> </td>
      </tr>
      </tfoot>
    </table>
<% end %>

app/views/layouts/administracao.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Administracao da Loja</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render  'compartilhados/admin_navbar' %>
<%= render  'compartilhados/mensagens' %>

<%= yield %>

<p>Feito por fellipe </p>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render  'compartilhados/navbar' %>
<%= render  'compartilhados/mensagens' %>

<%= yield %>

<p>Feito por fellipe </p>


</body>
</html>

app/views/produtos/index.html.erb
<h2>
  Lista de Produtos
</h2>

<p>
  <%= link_to( 'Novo produto',
          new_produto_url,
          :class => 'btn btn-primary' ) %>
</p>

<table class="table table-bordered table-striped">
  <%= render_head Produto, :nome, :preco, :quantidade %>
  <tbody>
    <% @produtos.each do |produto| %>
        <tr>
          <td><%= link_to( produto.nome,
                    produto_path(produto)  )%></td>
          <td><%= number_to_currency produto.preco %></td>
          <td>
           <%= form_tag itens_path, :method => :post do %>
             <%= hidden_field_tag :produto_id, produto.id %>
             <%= text_field_tag :quantidade, 1 %>
             <%= submit_tag 'Adicionar' %>
           <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/produtos/new.html.erb
<h2>
		Novo Produto
</h2>


<%= form_for @produto do |f| %>

<% unless @produto.errors.blank? %>
	<ul>
		<% @produto.errors.full_messages.each do |erro| %>
		<li> <%= erro %></li>
		<% end %>
	</ul>
	<% end %>

	<p>
		Nome: <%= f.text_field :nome %>
	</p>

	<p>
		Preco: <%= f.text_field :preco %>
	</p>

	<p>
		Descricao:
		<br/>
		<%= f.text_area :descricao %>
	</p>

	<p>
		<%= f.submit 'Enviar' %>
	</p>

<% end %>

app/views/produtos/show.html.erb
<h1> <%= @produto.nome %></h1>

<h2> Preco:
 <%= number_to_currency @produto.preco %>
</h2>

<p>
	<%= @produto.descricao %>
</p>